### ISSUE TITLE
11/20/2021: Upgrade Heroku Postgres to Standard & set up backups

### ISSUE THREAD

**Issue by ejaxon** [CodeForAsheville/court-notifications#102]

**Comment by ejaxon** [comment]
The production app is now running against a Standard-0 database, with daily backups. Also created credentials for the County data analyst to pull reports.

**Comment by jayhill** [comment]
@ejaxon Could you please expound on the access that the County Data Analyst has and how that arrangement came to be?

**Comment by ejaxon** [comment]
Sure. Per [this comment](https://github.com/CodeForAsheville/court-notifications/issues/13#issuecomment-954026538) I met with the analyst at the County that has been supporting the SJC efforts to reduce jail population to discuss what data could be used to measure and improve impact. As a result I added two reporting tables, one for subscriptions and one for notifications (```log_subscriptions``` and ```log_notifications```). The goal is to try to (a) use subscription information to keep encouraging the court system to promote the system and (b) try to assess the impact of notifications on reduced FTA rates. 

The primary reason for this is to try to make sure that we're having a positive impact. A secondary reason is that I want to have as much justification as possible in the event that the state court system decides to thwart our use of their public site to pull court date information.

The analyst has read-only access to these two tables, which do not include any subscriber information - only whether a subscription occurred or a notification was sent.
