### ISSUE TITLE
3/11/21: Improve Server Logging

### ISSUE THREAD

**Issue by colinalford** [CodeForAsheville/court-notifications#11]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Currently, I'm not logging much of anything, which means I have to troubleshoot locally whenever something goes down. I'd like to be able to pull the server logs from Heroku instead of trying to recreate the scenario on my local machine.

**Describe the solution you'd like**

- [ ] Add some package that will do better logging than what we currently have

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by ejaxon** [comment]
May want to use the same approach as the Anchorage CourtBot, [Winston](https://www.npmjs.com/package/winston) for logging and [Rollbar](https://rollbar.com/) to capture.
