### ISSUE TITLE
3/11/21: Improve Server Side Error Handling

### ISSUE THREAD

**Issue by colinalford** [CodeForAsheville/court-notifications#12]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'm guessing the app is brittle. Luckily, it is simple, so there isn't too much to worry about. Even so, if something goes wrong with the logic, I'd like to app to not completely crash.

**Describe the solution you'd like**

- [ ] Go through the server code and add in some error handling as needed

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by ejaxon** [comment]
Especially important for Twilio stuff - need to check the return message and note errors.
