### ISSUE TITLE
2022-07-30: Fix various awaits and implicitly declared variables in various scripts.

### ISSUE THREAD

**Issue by ejaxon** [CodeForAsheville/court-notifications#160]
There are a couple of places that should have the ```await``` keyword that @GKosheev found. They should be added.

**Comment by GKosheev** [comment]
I've found missing "await" keywords within server.js file as well (lines 66, 70, and 74).
Also, I found some redundant "await" keywords within ```migration``` folder

We can rename this issue so I can fix both missing and redundant "await" keywords.  



I also found implicitly declared variables in files:
"purge-and-update-subscriptions.js"  (line 38 and 51),
"twilio-send-status-webhook.js" (lines 31 and 44)

**Comment by ejaxon** [comment]
Renamed and assigned to you.

Just a heads up that I may be somewhat slow to respond to a pull request. Busy week and I'm traveling Thursday through Monday, so don't worry if I don't respond right away to things.

**Comment by GKosheev** [comment]
It's completely fine
