### ISSUE TITLE
08/28/21: Workday Tasks

### ISSUE THREAD

**Issue by colinalford** [CodeForAsheville/court-notifications#26]
- [x] Review the work Eric has done so far
- [x] Finish the purge & update script
- [x] Write the notification -- Go through, pull out records for those who need to be notified (assume we need a series e.g., 1 week, 3 days before, 1 day before, with different messages), and send Twilio message
- [x] Create webhook where if we get a STOP, we won't continue sending notifications
- [x] Create script that will create the database and tables 
- [x] Move Twilio server endpoints onto the main server
- [x] Setup with .env file and update references through the code base

**Comment by ejaxon** [comment]
@colinalford I have updated the ones I know are done here. Once you're done with the webhook work, let's close this and create discrete issues for remaining tasks.
