### ISSUE TITLE
10/22/2021: Privacy Policy

### ISSUE THREAD

**Issue by jayhill** [CodeForAsheville/court-notifications#76]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Since we collect phone numbers, I think it is important to provide information about how we handle and use that information.

**Describe the solution you'd like**
- [ ] Find a relevant example or model policy
- [ ] Adapt the policy for this system
- [ ] Have the policy translated into Russian & Spanish
- [ ] Provide a link to the policy in a footer

**Describe alternatives you've considered**
Or, just put a brief statement next to the phone number text field — something like:
> We won't share or use your phone number for anything other than sending court date reminders and we never store unencrypted phone numbers.

_Note: I'm not sure whether this last part is true. We also need to set up SSL._

**Comment by ejaxon** [comment]
Done, thanks to the help of Kristen Molina-Nauert!
