### ISSUE TITLE
2021-10-23: Clean up README

### ISSUE THREAD

**Issue by ejaxon** [CodeForAsheville/court-notifications#83]
## Feature Request

Make sure the README has clear instructions on how to run locally and change to use _yarn_ rather than _npm_.

**Comment by fatcatt316** [comment]
Hey @ejaxon , I learned about this project at the open house last week, and started on this issue today, but ran into a wee spreedbump.

For the first step in the README, it says `cp .env.sample .env`, but I don't see a `.env.sample` file.

Should this say `cp packages/server/sample.env packages/server/env` or something like that?

**Comment by ejaxon** [comment]
Hi @fatcatt316. There was a major reorganization of the code recently (still playing out the consequences of that, actually). Until a few weeks ago that instruction was correct. I think probably you're probably right that now it's 
```
cp packages/server/sample.env packages/server/.env
```
tho I'd have to double check (unfortunately, I'm not going to get to anything before Saturday).

**Comment by fatcatt316** [comment]
@ejaxon Ah that makes sense. I might monkey around with it a bit, but if you figure it out before me and leave a comment on this issue, I'm happy to keep pushing on updating the README.

**Comment by ejaxon** [comment]
There's probably more to do here, but I have updated all the development set up instructions to match the current version of the code.

Closing this for now. Future fixes should focus on specific areas.
